### ISSUE TITLE
Doesn't work on remote files

### ISSUE THREAD

**Issue by ghost** [mkxml/atom-filesize#19]
Presumably on any remote file system, though I'm using nuclide.

Can the # of characters just be counted instead of hitting the filesystem?

**Comment by mkxml** [comment]
Interesting. I didn't test that scenario. It should work given the correct address, since I'm just using `fs` under the hood. Need to check what info Atom is passing to `atom-filesize` in this particular case.

The package is meant to show the file size and info of any file and encoding formats, this is why I'm hitting the filesystem to get the info so I don't have to consider the many edge cases.

Can you provide me info about the OS you are using and the Atom version?

**Comment by ghost** [comment]
The problem is that `fs.open(nuclide://...)` doesn't exist -- nuclide (somehow) proxies all the file ops through to a remote server.  I imagine other plugins that use `ftp://`, `sftp://`, `scp://`, etc have the same issue, though I don't use any of them.

Would something like this be acceptable (unsure of exact APIs):

    function getFileSize(path, editor) {
      try {
        return fs.stat(path).size;
      } catch(err) {
        return editor.toString().length;
      }
    }

Granted you'd lose knowledge of unicode encodings and increased file size due to it, not sure if that's acceptable or not

**Comment by mkxml** [comment]
Fixed and released in `4.0.0`. Used your approach. Thank you @zyklus! Its basic support for now, may improve in the future.
